// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// SECURITY FIX: Use environment variables instead of hardcoded keys
const SUPABASE_URL = "https://kscemqgnqpqtukaeadie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzY2VtcWducXBxdHVrYWVhZGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDQ2MjgsImV4cCI6MjA3MjgyMDYyOH0.0pWzxtcIaro6CCyLE0eYnxg1sAAIHAjXrJmnx5AyDzk";

// Validate required environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing required Supabase configuration. Please check your project setup.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SECURITY FIX: Use secure storage instead of localStorage
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'trading-app-auth',
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-application-name': 'trading-analytics-platform'
    }
  }
});